### ISSUE TITLE
Dependency relocated

### ISSUE THREAD

**Issue by petemoore** [dchest/uniuri#10]
See https://travis-ci.org/taskcluster/taskcluster/generic-worker/jobs/87917365#L143

Is this because uniuri is pointing to an old location of this dependency?

**Comment by dchest** [comment]
I'm not sure what's wrong with this log, but uniuri doesn't import any third-party packages at all, and the only import is `crypto/rand` from the standard library: https://github.com/dchest/uniuri/blob/master/uniuri.go#L25

**Comment by petemoore** [comment]
Sorry, my mistake. I found the source, and it was another repo. Thanks for quick reply!
