### ISSUE TITLE
Shouldn't panic

### ISSUE THREAD

**Issue by tbruyelle** [dchest/uniuri#11]
As a third party library, you shouldn't invoke `panic()` but return an error and let the client deal with the error.

**Comment by dchest** [comment]
In general, you're right, but PRNG failure is a different case.

Random number generator failure is an unrecoverable error, as most programs cannot continue to function properly and securely without it. There is a lot of evidence that aborting the program in case of PRNG failure is the best thing libraries can do to improve security, as programmers do not check errors. That is why operating systems are now integrating random number generators that don't return errors:

* OpenBSD's `getentropy` — http://www.openbsd.org/cgi-bin/man.cgi/OpenBSD-current/man2/getentropy.2?query=getentropy&sec=2
* Solaris `getentropy` and `getrandom` — https://blogs.oracle.com/darren/entry/solaris_new_system_calls_getentropy
* Linux `getrandom` — https://lwn.net/Articles/606141/

...and Go uses them.

**Comment by tbruyelle** [comment]
Thanks for the detailled response.
