### ISSUE TITLE
About the CC0 license

### ISSUE THREAD

**Issue by dhruv** [dchest/uniuri#13]
Since CC0 and public domain are not universally recognized formats for open-source code, would you be willing to license under MIT, Apache, BSD, or any of the OSI-approved licenses mentioned here?: https://opensource.org/licenses

**Comment by dchest** [comment]
No, sorry. I released a lot of code under CC0 and I'm not going to waste time relicensing it all because some lawyers are confused about public domain or CC0. Companies who need some kind of a custom license are free to contact me to discuss terms ;-)
