### ISSUE TITLE
LICENSE or COPYING file

### ISSUE THREAD

**Issue by gauntface** [dchest/uniuri#15]
It would be super helpful to include a LICENSE or COPYING file in your repo.

https://wiki.creativecommons.org/wiki/CC0_FAQ#May_I_apply_CC0_to_computer_software.3F_If_so.2C_is_there_a_recommended_implementation.3F

Recommends using:
https://creativecommons.org/publicdomain/zero/1.0/legalcode.txt

**Comment by dchest** [comment]
I hate files :) The CC0 blurb is currently in the code and README. Is there an additional reason to have it in COPYING/LICENSE apart from GitHub parsing it? Automated tools that extract licenses from packages maybe? What's your specific concern?

**Comment by gauntface** [comment]
It's largely to make it clear that you are licensing the project under CC0. Without the LICENSE text (which the majority of human and automated reviewers rely on), it's difficult to allow use of this project in a fast manor without further investigation.

**Comment by johnaoss** [comment]
+1 for this, especially considering pkg.go.dev won't show package documentation unless it has an OSI approved license (which unfortunately CC0 is not as explained in the OSI FAQ https://opensource.org/faq#cc-zero). 

Still though it's a big help for automated tools to have a LICENSE file.
